config/routes.rb
SDZZ::Application.routes.draw do
  
  resources :leaguetables

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get 'stories/privacystatement' 

  resources :stories do
  	resources :storycomments
  end

  resources :posts do
  	resources :comments
  end

  resources :home

  root :to => 'home#index'

end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :description, :image, :remote_image_url, :title
  mount_uploader :image, ImageUploader
  has_many :storycomments, :dependent => :destroy
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.find(:all, :order => 'created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(params[:story])

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Storie is geplaatst, lekkur!' }
        format.json { render json: @story, status: :created, location: @story }
      else
        format.html { render action: "new" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to @story, notice: 'Schitterend!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for @story, :html => {:multipart => true} do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Titel" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description, "Achtergrond Story" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :remote_image_url, "of afbeelding via URL" %><br />
    <%= f.text_field :remote_image_url %>
  </div>
  <div class="actions">
    <%= f.submit "Plaats die story!" %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Terug', @story %>

app/views/stories/index.html.erb
<h1>The Stories</h1>

<% @stories.each do |story| %>
<li><%= link_to story.title, story %>|<%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></li>
<% end %>

<br />

<%= link_to 'Nieuwe story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/privacystatement.html.erb
<h2>Ingrijpen bij reacties</h2>
<p>
Verwijderen van berichten
Het verwijderen van ongepaste berichten komt relatief vaak voor. Dit mag, als het bericht tegen de regels van het forum is. Maar de beheerders hebben wel een bewijslast. Ze moeten zich houden aan de regels die in het reglement zijn vastgelegd. Als daar bijvoorbeeld in staat dat geen reclame mag worden gemaakt, dan mogen ze berichten verwijderen die reclame bevatten. Het reglement mag bijvoorbeeld ook deelname door minderjarigen verbieden.
</p>
<p>
Dat wil niet zeggen dat alles wat niet niet verboden is, dus zonder meer toegestaan is. Een beheerder mag bijvoorbeeld best ingrijpen bij illegale activiteiten, zoals racistische uitlatingen of uitleg hoe een beveiliging van software of muziek te kraken is. Ook als dit niet expliciet in het reglement staat.
</p>
<p>
Verwijderen op verzoek
Soms komt het voor dat een deelnemer zelf vraagt om een bericht te laten verwijderen. Een bericht op een forum is volgens de privacywet een persoonsgegeven, en dat moet worden verwijderd als de betrokken persoon daarom vraagt. Dit blijkt uit de Richtsnoeren privacy op internet (PDF) van het College Bescherming Persoonsgegevens.
</p>
<p>
De enige reden om het te mogen laten staan, is als er een "eigen gerechtvaardigd belang bij publicatie" is. Zo'n belang kan bijvoorbeeld zijn dat door de verwijdering de discussie onbegrijpelijk wordt. In dat geval, zo zeggen de richtlijnen, kun je volstaan met de naam van de plaatser vervangen door [VERWIJDERD] of iets dergelijks. Tenzij de inhoud van het bericht zelf nog informatie over de plaatser bevat, dan zou die informatie moeten worden geschrapt.
</p>
<p>
Zie: <a href="http://www.iusmentis.com/websites/forums/" target='_blank'>website link met standaard policies en regelgeving</a>
</p>
<br />
<%= link_to 'Zuruck jawohl!', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @story.title %></h1>
<p>
  <b>Achtergrond Story:</b>
  <%= @story.description %>
</p>

<p>
  <b>Image:</b>
  <center>
  <%= image_tag @story.image_url(:thumb).to_s %>
  </center>
</p>

<h2>Gevatte opmerkingen</h2>
<%= render @story.storycomments %>

<h3>Deel je intellectuele hoogstandje:</h3>
<%= render 'storycomments/form' %>

<br />


<%= link_to 'Eventjes wijzigen', edit_story_path(@story) %> |
<%= link_to 'Zuruck jawohl!', stories_path %>|<%= link_to 'Privacy Statement', stories_privacystatement_path %>