config/routes.rb
SDZZ::Application.routes.draw do
  
  resources :leaguetables

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get 'stories/privacystatement' 

  resources :stories do
  	resources :storycomments
  end

  resources :posts do
  	resources :comments
  end

  resources :home

  root :to => 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Een meesterwerk is geplaast, lekkur!' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Slim, eventjes gewijzigd, stukken beter zo!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Terug', @post %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<% @posts.each do |post| %>
    <hr />
    <%= link_to post.title, post %>|<%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %><br />
    <%= truncate(post.content, :length => 100, :omission => '...') %>
    <hr />
  
<% end %>


<br />

<%= link_to 'Nieuw Artikel', new_post_path %>|
<%= link_to 'Homepage', home_index_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% content_for :head do %>
  <%= tag :meta, property: "fb:app_id", content: "477453758950604" %>
  <%= tag :meta, property: "og:site_name", content: "Talentjes" %>
  <%= tag :meta, property: "og:type", content: "talentjes:blog" %>
  <%= tag :meta, property: "og:title", content: @post.name %>
  <%= tag :meta, property: "og:url", content: post_url(@post) %>
  <%= tag :meta, property: "og:image", content: "https://s-static.ak.fbcdn.net/images/devsite/attachment_blank.png" %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Name:</b>
  <%= @post.name %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>
<hr />
<h2>Comments</h2>
<%= render @post.comments %>
<hr />

<h2>Add a comment:</h2>
<%= render "comments/form" %>


<%= link_to 'Eventjes wijzigen', edit_post_path(@post) %> |
<%= link_to 'Terug naar overzicht', posts_path %>