config/routes.rb
SDZZ::Application.routes.draw do
  
  resources :leaguetables

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  get 'stories/privacystatement' 

  resources :stories do
  	resources :storycomments
  end

  resources :posts do
  	resources :comments
  end

  resources :home

  root :to => 'home#index'

end

app/controllers/leaguetables_controller.rb
class LeaguetablesController < ApplicationController
  # GET /leaguetables
  # GET /leaguetables.json
  def index
    @leaguetables = Leaguetable.find(:all, :order => 'points - penalty_points DESC, matches_played, goals_for - goals_against DESC, goals_for DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leaguetables }
    end
  end

  # GET /leaguetables/1
  # GET /leaguetables/1.json
  def show
    @leaguetable = Leaguetable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leaguetable }
    end
  end

  # GET /leaguetables/new
  # GET /leaguetables/new.json
  def new
    @leaguetable = Leaguetable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leaguetable }
    end
  end

  # GET /leaguetables/1/edit
  def edit
    @leaguetable = Leaguetable.find(params[:id])
  end

  # POST /leaguetables
  # POST /leaguetables.json
  def create
    @leaguetable = Leaguetable.new(params[:leaguetable])

    respond_to do |format|
      if @leaguetable.save
        format.html { redirect_to @leaguetable, notice: 'Leaguetable was successfully created.' }
        format.json { render json: @leaguetable, status: :created, location: @leaguetable }
      else
        format.html { render action: "new" }
        format.json { render json: @leaguetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leaguetables/1
  # PUT /leaguetables/1.json
  def update
    @leaguetable = Leaguetable.find(params[:id])

    respond_to do |format|
      if @leaguetable.update_attributes(params[:leaguetable])
        format.html { redirect_to @leaguetable, notice: 'Leaguetable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leaguetable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaguetables/1
  # DELETE /leaguetables/1.json
  def destroy
    @leaguetable = Leaguetable.find(params[:id])
    @leaguetable.destroy

    respond_to do |format|
      format.html { redirect_to leaguetables_url }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/leaguetables_helper.rb
module LeaguetablesHelper
end

app/views/leaguetables/_form.html.erb
<%= form_for(@leaguetable) do |f| %>
  <% if @leaguetable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leaguetable.errors.count, "error") %> prohibited this leaguetable from being saved:</h2>

      <ul>
      <% @leaguetable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :club_name %><br />
    <%= f.text_field :club_name %>
  </div>
  <div class="field">
    <%= f.label :club_id %><br />
    <%= f.number_field :club_id %>
  </div>
  <div class="field">
    <%= f.label :matches_played %><br />
    <%= f.number_field :matches_played %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :wins %><br />
    <%= f.number_field :wins %>
  </div>
  <div class="field">
    <%= f.label :draws %><br />
    <%= f.number_field :draws %>
  </div>
  <div class="field">
    <%= f.label :losses %><br />
    <%= f.number_field :losses %>
  </div>
  <div class="field">
    <%= f.label :goals_for %><br />
    <%= f.number_field :goals_for %>
  </div>
  <div class="field">
    <%= f.label :goals_against %><br />
    <%= f.number_field :goals_against %>
  </div>
  <div class="field">
    <%= f.label :penalty_points %><br />
    <%= f.number_field :penalty_points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leaguetables/edit.html.erb
<h1>Editing leaguetable</h1>

<%= render 'form' %>

<%= link_to 'Show', @leaguetable %> |
<%= link_to 'Back', leaguetables_path %>

app/views/leaguetables/index.html.erb
<h1>Listing leaguetables</h1>

<table border="1">
  <tr>
    <th width="200pt" align="left">Club name</th>
    <th>Gespeeld</th>
    <th width="75pt" align="center">Winst</th>
    <th width="75pt" align="center">Gelijk</th>
    <th width="75pt" align="center">Verlies</th>
    <th width="75pt" align="center">Voor</th>
    <th width="75pt" align="center">Tegen</th>
    <th width="75pt" align="center">Doelsaldo</th>
    <th width="75pt" align="center">Punten</th>
    <th width="75pt" align="center">Strafpunten</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leaguetables.each do |leaguetable| %>
  <tr>
    <td><b><%= leaguetable.club_name %><b></td>
    <td align="center"><%= leaguetable.matches_played %></td>
    <td align="center"><%= leaguetable.wins %></td>
    <td align="center"><%= leaguetable.draws %></td>
    <td align="center"><%= leaguetable.losses %></td>
    <td align="center"><%= leaguetable.goals_for %></td>
    <td align="center"><%= leaguetable.goals_against %></td>
    <td align="center"><%= leaguetable.goal_difference %></td>
    <td align="center"><b><%= leaguetable.pointz %></b></td>
    <td align="center"><%= leaguetable.penalty_points %></td>
    <td align="center"><%= link_to 'Show', leaguetable %></td>
    <td align="center"><%= link_to 'Edit', edit_leaguetable_path(leaguetable) %></td>
    <td align="center"><%= link_to 'Destroy', leaguetable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Leaguetable', new_leaguetable_path %>

app/views/leaguetables/new.html.erb
<h1>New leaguetable</h1>

<%= render 'form' %>

<%= link_to 'Back', leaguetables_path %>

app/views/leaguetables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Club name:</b>
  <%= @leaguetable.club_name %>
</p>

<p>
  <b>Club:</b>
  <%= @leaguetable.club_id %>
</p>

<p>
  <b>Matches played:</b>
  <%= @leaguetable.matches_played %>
</p>

<p>
  <b>Points:</b>
  <%= @leaguetable.points %>
</p>

<p>
  <b>Wins:</b>
  <%= @leaguetable.wins %>
</p>

<p>
  <b>Draws:</b>
  <%= @leaguetable.draws %>
</p>

<p>
  <b>Losses:</b>
  <%= @leaguetable.losses %>
</p>

<p>
  <b>Goals for:</b>
  <%= @leaguetable.goals_for %>
</p>

<p>
  <b>Goals against:</b>
  <%= @leaguetable.goals_against %>
</p>

<p>
  <b>Penalty points:</b>
  <%= @leaguetable.penalty_points %>
</p>


<%= link_to 'Edit', edit_leaguetable_path(@leaguetable) %> |
<%= link_to 'Back', leaguetables_path %>